name: CI

on: [push]

jobs:
  testStuffOut:
    runs-on: windows-latest
    steps:
    - name: install dependencies
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        iwr -useb get.scoop.sh | iex
        scoop install openssl frp
        scoop info openssl
        scoop info frp
    - name: check
      run: |
        env
        tasklist
        netstat -a
    - name: main
      run: |
        git clone https://github.com/ntop/n2n.git
        cd n2n
        md build
        cd build
        cmake ..
