name: Build n2n

on: [push]

jobs:
  testStuffOut:
    runs-on: windows-latest
    steps:
    - name: install dependencies
      run: |
        Set-ExecutionPolicy RemoteSigned -scope CurrentUser
        iwr -useb get.scoop.sh | iex
        scoop bucket add extras
        scoop install openssl frp vswhere
        scoop info openssl
        scoop info frp
        vswhere
    - name: check
      run: |
        env
        tasklist
        netstat -a
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: main
      run: |
        ls C:\Users\runneradmin\scoop\apps\openssl\1.1.1d
        git clone https://github.com/ntop/n2n.git
        cd n2n
        md build
        cd build
        cmake -D OPENSSL_ROOT_DIR=C:\Users\runneradmin\scoop\apps\openssl\1.1.1d -D OPENSSL_CRYPTO_LIBRARY=C:\Users\runneradmin\scoop\apps\openssl\1.1.1d\lib ..
        msbuild edge.vcxproj /t:Build /p:Configuration=Release
        msbuild supernode.vcxproj /t:Build /p:Configuration=Release
        ls D:\a
    - uses: actions/upload-artifact@master
      with:
        name: Upload
        path: D:\a
