name: RDP

on:
  push:
    paths:
    - '.github/workflows/'
    
jobs:
  start:
    runs-on: windows-latest
    steps:
      - name: Install
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iwr -useb get.scoop.sh | iex
          scoop bucket add extras
          scoop install frp
      - name: Run
        run: |
          frpc -h
