name: RDP

on:
  workflow_dispatch:
    
jobs:
  start:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Expose Windows RDP
        env:
          RDP_PASSWD: ${{ secrets.RDP_PASSWD }}
        run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iwr -useb get.scoop.sh | iex
          scoop bucket add extras
          scoop install busybox frp
          sh rdp.sh
      - name: Wait
        shell: bash
        run:
          sleep $((3600*6))
