name: RDP

on:
  workflow_dispatch:

env:
  MORE_DISK_SPACE: true

jobs:
  start:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
#       - uses: brechtm/setup-scoop@v2
#         with:
#           scoop_update: 'false'
      - name: Expose Windows RDP
        env:
          RDP_PASSWD: ${{ secrets.RDP_PASSWD }}
        run: |
          echo $env:UserName
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm get.scoop.sh | iex
          scoop bucket add extras
          scoop install busybox frp aria2
          sh rdp.sh
      - name: More disk space
        shell: bash
        run: pwd
#       - name: More disk space
#         run: |
#           rd /s /q "C:\msys64"
#           rd /s /q "C:\hostedtoolcache"
#           rd /s /q "C:\Program Files (x86)\Android"
#           rd /s /q "C:\Program Files (x86)\Google"
#           rd /s /q "C:\Program Files (x86)\Microsoft SDKs"
#           rd /s /q "C:\Program Files (x86)\Windows Kits"
#           for /d %G in ("C:\Program Files (x86)\Microsoft Visual Studio*") do rd /s /q "%~G"
#         shell: cmd
#         if: env.MORE_DISK_SPACE == 'true'
      - name: Wait
        shell: bash
        run:
          sleep $((3600*6))
