name: RDP

on:
  workflow_dispatch:
    
jobs:
  start:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Init
        env:
          RDP_PASSWD: ${{ secrets.RDP_PASSWD }}
          RDP_FRPC_CONF: ${{ secrets.RDP_FRPC_CONF }}
        run: |
          net user
          net user runneradmin "$env:RDP_PASSWD"
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iwr -useb get.scoop.sh | iex
          scoop bucket add extras
          scoop install busybox frp
          ls
          echo "$env:RDP_FRPC_CONF" > frpc.ini
